// Copyright 2025 Umberto Gotti <umberto.gotti@umbertogotti.dev>
// Licensed under the MIT License
// SPDX-License-Identifier: MIT

pub mod args_tests;
pub mod baseline_outcome_tests;
pub mod baseline_tests;
pub mod column_widths_tests;
pub mod config_file_tests;
pub mod exclusion_outcome_tests;
pub mod exclusion_set_tests;
pub mod exclusion_tests;
pub mod header_source_tests;
pub mod implemented_type_finder_tests;
pub mod implemented_type_tests;
pub mod import_path_tests;
pub mod json_printer_tests;
pub mod manifest_resolver_tests;
pub mod module_declaration_finder_tests;
pub mod offence_fingerprint_tests;
pub mod offence_tests;
pub mod offence_threshold_tests;
pub mod output_format_tests;
pub mod package_tree_tests;
pub mod qualified_call_finder_tests;
pub mod qualified_call_tests;
pub mod registry_item_tests;
pub mod registry_parser_tests;
pub mod registry_policy_tests;
pub mod report_printer_tests;
pub mod rule_registry_tests;
pub mod rule_selection_tests;
pub mod rules;
pub mod run_outcome_tests;
pub mod runner_tests;
pub mod section_tests;
pub mod source_file_tests;
pub mod source_reader_tests;
pub mod source_walker_tests;
pub mod test_file_item_tests;
pub mod test_file_parser_tests;
pub mod unit_test_finder_tests;
pub mod unit_test_site_tests;
